{
  "tracks": {
    "href": "https://api.spotify.com/v1/search?query=The+Sign&type=track&market=US&offset=0&limit=20",
    "items": [
      {
        "album": {
          "album_type": "album",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6KImCVD70vtIoJWnq6nGn3"
              },
              "href": "https://api.spotify.com/v1/artists/6KImCVD70vtIoJWnq6nGn3",
              "id": "6KImCVD70vtIoJWnq6nGn3",
              "name": "Harry Styles",
              "type": "artist",
              "uri": "spotify:artist:6KImCVD70vtIoJWnq6nGn3"
            }
          ],
          "available_markets": [
            "AD",
            "AR",
            "AT",
            "AU",
            "BE",
            "BG",
            "BO",
            "BR",
            "CA",
            "CH",
            "CL",
            "CO",
            "CR",
            "CY",
            "CZ",
            "DE",
            "DK",
            "DO",
            "EC",
            "EE",
            "ES",
            "FI",
            "FR",
            "GB",
            "GR",
            "GT",
            "HK",
            "HN",
            "HU",
            "ID",
            "IE",
            "IL",
            "IS",
            "IT",
            "JP",
            "LI",
            "LT",
            "LU",
            "LV",
            "MC",
            "MT",
            "MX",
            "MY",
            "NI",
            "NL",
            "NO",
            "NZ",
            "PA",
            "PE",
            "PH",
            "PL",
            "PT",
            "PY",
            "RO",
            "SE",
            "SG",
            "SK",
            "SV",
            "TH",
            "TR",
            "TW",
            "US",
            "UY",
            "VN",
            "ZA"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1FZKIm3JVDCxTchXDo5jOV"
          },
          "href": "https://api.spotify.com/v1/albums/1FZKIm3JVDCxTchXDo5jOV",
          "id": "1FZKIm3JVDCxTchXDo5jOV",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/d4e1e36b7115e645dc6fd432cdd3ea7c0c4d939a",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/2faf14c121b01bde63b55fdc9fbb3ddeec2ad48d",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/f842de1f2db71f3b1a0eb6172b4d33615edaa0ca",
              "width": 64
            }
          ],
          "name": "Harry Styles",
          "release_date": "2017-05-12",
          "release_date_precision": "day",
          "total_tracks": 10,
          "type": "album",
          "uri": "spotify:album:1FZKIm3JVDCxTchXDo5jOV"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6KImCVD70vtIoJWnq6nGn3"
            },
            "href": "https://api.spotify.com/v1/artists/6KImCVD70vtIoJWnq6nGn3",
            "id": "6KImCVD70vtIoJWnq6nGn3",
            "name": "Harry Styles",
            "type": "artist",
            "uri": "spotify:artist:6KImCVD70vtIoJWnq6nGn3"
          }
        ],
        "available_markets": [
          "AD",
          "AR",
          "AT",
          "AU",
          "BE",
          "BG",
          "BO",
          "BR",
          "CA",
          "CH",
          "CL",
          "CO",
          "CR",
          "CY",
          "CZ",
          "DE",
          "DK",
          "DO",
          "EC",
          "EE",
          "ES",
          "FI",
          "FR",
          "GB",
          "GR",
          "GT",
          "HK",
          "HN",
          "HU",
          "ID",
          "IE",
          "IL",
          "IS",
          "IT",
          "JP",
          "LI",
          "LT",
          "LU",
          "LV",
          "MC",
          "MT",
          "MX",
          "MY",
          "NI",
          "NL",
          "NO",
          "NZ",
          "PA",
          "PE",
          "PH",
          "PL",
          "PT",
          "PY",
          "RO",
          "SE",
          "SG",
          "SK",
          "SV",
          "TH",
          "TR",
          "TW",
          "US",
          "UY",
          "VN",
          "ZA"
        ],
        "disc_number": 1,
        "duration_ms": 340706,
        "explicit": false,
        "external_ids": {
          "isrc": "USSM11703595"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5Ohxk2dO5COHF1krpoPigN"
        },
        "href": "https://api.spotify.com/v1/tracks/5Ohxk2dO5COHF1krpoPigN",
        "id": "5Ohxk2dO5COHF1krpoPigN",
        "is_local": false,
        "name": "Sign of the Times",
        "popularity": 81,
        "preview_url": "https://p.scdn.co/mp3-preview/af237206f611b722f48620ece049aff3b8650e77?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 2,
        "type": "track",
        "uri": "spotify:track:5Ohxk2dO5COHF1krpoPigN"
      },